name: Build and Deploy to Azure Container Instance

on:
  push:
    branches:
      - TP3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: efreidevops.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/2019484:v1

      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          name: 20190484
          resource-group: ADDA84-CTP
          dns-name-label: devops-2019484
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20190484:v1
          registry-login-server: efreidevops.azurecr.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          location: francecentral
